import HomeHeader from "@/components/header/HomeHeader";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Copyright } from "lucide-react";
import { Github, Mail, Twitter, Linkedin } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative `}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="sticky -z-10 top-0">
            <div className="-top-32 right-32 absolute h-48 w-1/2 blur-[80px] rounded-full bg-fuchsia-500"></div>
            <div className="-top-32 left-32 absolute h-48 w-1/2 blur-[80px] rounded-full bg-blue-500"></div>
          </div>

          <HomeHeader></HomeHeader>
          {children}
          <footer className="max-w-7xl w-full mx-auto flex p-8 justify-between items-center ">
            <div className="flex gap-8 items-center">
              <span className="flex gap-2 items-center text-sm">
                <Copyright className="w-8" size={16} /> visheshdubey, 2023
              </span>
              <div className="flex gap-4">
                <a
                  href="http://#"
                  className={buttonVariants({
                    variant: "ghost",
                    size: "icon",
                  })}
                >
                  <Github className={` w-5 stroke-muted-foreground`} />
                </a>
                <a
                  href="http://#"
                  className={buttonVariants({
                    variant: "ghost",
                    size: "icon",
                  })}
                >
                  <Linkedin className="w-5 stroke-muted-foreground" />
                </a>
                <a
                  href="http://#"
                  className={buttonVariants({
                    variant: "ghost",
                    size: "icon",
                  })}
                >
                  <Twitter className="w-5 stroke-muted-foreground" />
                </a>
                <a
                  href="http://#"
                  className={buttonVariants({
                    variant: "ghost",
                    size: "icon",
                  })}
                >
                  <Mail className="w-5 stroke-muted-foreground" />
                </a>
              </div>
            </div>
            <span className="text-muted-foreground">
              Iterate.Innovate.Inspire!
            </span>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
